### ISSUE TITLE
Illegal  Product implementation

### ISSUE THREAD

**Issue by SergeiYakimchik** [zolkiBy/JavaTraining#2]
https://github.com/zolkiBy/JavaTraining/blob/9bc8c18b1de8c3deff24d28013d6ecee3a87f676/Lesson2/Task3/src/com/company/product/TankProduct.java#L12

Эти методы - это обычные сеттеры, по схеме продукт агрегирует детали продукта. Следовательно необходимо добавить детали продукта в переменки

**Comment by zolkiBy** [comment]
add one more commit
